### ISSUE TITLE
Creating an hierarchy always select the first item

### ISSUE THREAD

**Issue by JonathanPicques** [dudeteam/dude-hierarchy#10]
It should not select the first item automatically, we could use a property "auto-select"
Also, when the first item is selected, no event is triggered (item-click - dude-hierarchy-select-item)

**Comment by jeremt** [comment]
Yes, it should. Otherwise, it means that you can validate a selection without selecting anything that's why it's selected by default.

**Comment by maxperrimond** [comment]
An attribute "autoSelect" can be set to false but otherwise the first item is always selected
